name: Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand what you'd like to see.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Template
        - New Feature Module
        - Enhancement to Existing Feature
        - New Shared Component
        - Tooling/DevEx Improvement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I'd like to have...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: |
        If you have ideas about how this could be implemented, share them here.
        Include technical details, file structure, or pseudocode if relevant.
      placeholder: |
        This could be implemented by...
        Files to add/modify:
        -

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (a few hours)
        - Medium (a few days)
        - High (a week or more)
        - Unknown
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I'd like to work on this feature
        - label: I need help implementing this
        - label: I'm just suggesting the idea

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and PRs to ensure this hasn't been suggested before
          required: true
        - label: This feature aligns with the project's goals and architecture
          required: true
